### ISSUE TITLE
tcsplot does not show plot in Linux

### ISSUE THREAD

**Issue by aacocucci** [rmaia/pavo#232] opened 2021-07-13 17:34 UTC
Hi, I'm trying to plot a tetrahedron with tcsplot. I use the example given in the documentation. The scripts run ok, the data tables are there, no errors or warnings but the plot does not show up. I work with Ubuntu 18.04, pavo 2.7 and Rstudio 1.4.1717.
I have also tried running the script in the R console outside Rstudio but the problem persists.
In Windows the same script does show up as expected.
Any suggestions what may be happening?

**Comment by Bisaloo** [comment] 2021-07-15 07:15
Hi,

I can reproduce your issue but I have the same problem when I try to run example from rgl so I would say that it comes from either rgl or RStudio, not from pavo.

You can check with this example from `?rgl::plot3d`:

```r
library(rgl)
open3d()
x <- sort(rnorm(1000))
y <- rnorm(1000)
z <- rnorm(1000) + atan2(x, y)
plot3d(x, y, z, col = rainbow(1000))
```

**Comment by Bisaloo** [comment] 2021-07-15 07:19
When I load rgl, I get the following message:

> This build of rgl does not include OpenGL functions.  Use
 rglwidget() to display results, e.g. via options(rgl.printRglwidget = TRUE)

And if I run `options(rgl.printRglwidget = TRUE)`, the plot opens in my web browser. So it might be an intended breaking change from their end.

**Comment by Bisaloo** [comment] 2021-07-15 07:24
Or simpler:

```r
library(pavo)
data(sicalis)
vis.sicalis <- vismodel(sicalis, visual = "avg.uv")
tcs.sicalis <- colspace(vis.sicalis, space = "tcs")
tcsplot(tcs.sicalis, size = 0.005)
rgl::rglwidget()
```

**Comment by Bisaloo** [comment] 2021-07-20 14:13
Closing this issue since it doesn't come from us and I offered a way around it. Feel free to reach out if you are more problems :wink:

**Closed by Bisaloo** 2021-07-20 14:13 UTC
